mongodb/go-client-mongodb-atlas

mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshot_restore_jobs_test.go, mongodbatlas/cloud_provider_snapshots_test.go, mongodbatlas/mongodbatlas.go
Added:
- cloud_provider_snapshot_restore_jobs file to handle API calls.
- cloud_provider_snapshot_restore_jobs_test file to Test.
https://docs.atlas.mongodb.com/reference/api/cloud-provider-snapshot-restore-jobs/
=> Cloud Provider Snapshot Restore Job Support

mongodbatlas/encryptions_at_rest.go, mongodbatlas/encryptions_at_rest_test.go, mongodbatlas/mongodbatlas.go
Added:
- encryptions_at_rest file to handle API calls.
- encryptions_at_rest_test file to Test.
https://docs.atlas.mongodb.com/reference/api/encryption-at-rest/
=>  Encryption At Rest Service

mongodbatlas/api_keys.go, mongodbatlas/mongodbatlas.go, mongodbatlas/project_api_key.go, mongodbatlas/whitelist_api_keys.go, mongodbatlas/whitelist_api_keys_test.go
Added:
whitelist_api_keys file to handle API calls.
whitelist_api_keys_test file to Test.
https://docs.atlas.mongodb.com/reference/api/apiKeys/
=> Whitelist API Keys

mongodbatlas/clusters.go
- Added default disk size map for each provider tier
It can be use as a following: 
`DefaultDiskSizeGB["AWS"]["M10"]`
This new feature is necessary to use it on the Terraform cluster resource to define the disk size automatically.
If you have a comment just let me know, thanks.
=> chore: added default disk size for each provider tier

mongodbatlas/custom_db_roles.go, mongodbatlas/custom_db_roles_test.go, mongodbatlas/mongodbatlas.go
I created a new service for operating the API for Custom MongoDB Roles. This is in preparation for adding a new resource for roles to the Terraform MongoDB Atlas provider.
Tried to follow the conventions of the rest of the code. Thinks I wasn't sure about:
* whether I should enumerate somewhere the possible [Custom Role Actions](https://docs.atlas.mongodb.com/reference/api/custom-role-actions/), but I figured these might change with time and perhaps are better left as plain strings.
* whether I should also test paging parameters, because the response structure for the Custom MongoDB Roles list is different from the other APIs -- does not have `Links`, `Results` nor `TotalCount`.
I can, of course, add both of the above, if so requested.
=> Service for manipulating Custom MongoDB Roles

mongodbatlas/atlas_users.go, mongodbatlas/atlas_users_test.go, mongodbatlas/clusters.go, mongodbatlas/mongodbatlas.go, mongodbatlas/teams.go
Add Atlas Users Service to perform the following requests:
1. Get all users from the project.
2. Get by ID
3. Get by Username
4. Create Atlas Users.
> **NOTE**: We are pending with Update and Delete Atlas User since these calls are not enabled in the public API.
=> Atlas Users Service

mongodbatlas/teams.go, mongodbatlas/teams_test.go
- Rename the `AddUserToTeam` to `AddUsersToTeam`
- Left the current API behavior on `AddUsersToTeam` function, allows an array of users's id like a parameter to add them to the Team.
- The test improved checking the expected behavior.
=> changed the AddUsersToTeam function to allow a string array of users id

GNUmakefile, mongodbatlas/clusters.go, mongodbatlas/encryptions_at_rest.go, mongodbatlas/global_clusters_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/peers.go, mongodbatlas/private_ip_mode.go, mongodbatlas/private_ip_mode_test.go, mongodbatlas/projects.go, mongodbatlas/projects_test.go
This enables golint to be run as part of make lint and fixes some warnings flagged by it
this aims to make the codebase more homogenous as part of the code seemed to be linted and other not
**Warning**: this may be a breaking change as the name of some public interfaces are changing
=> Enable golint and fix errors

mongodbatlas/custom_db_roles.go, mongodbatlas/custom_db_roles_test.go
- Changed the Cluster attribute to a pointer due that it is a bool type and the resource needs to identify when it's false.
- Fixed the test cases due to the Cluster attribute change.
- Some comments were improved to avoid warnings.
=> Custom DB Roles

mongodbatlas/database_users.go, mongodbatlas/database_users_test.go
Added: 
* The x509Type parameter was added into the DatabaseUser struct because it's necessary for the users created and when it pretends to use the x509 auth database users resource to configure the auth. 
* A test case was added to verify the request and response using the x509Type parameter.
=> Database Users

mongodbatlas/x509_authentication_database_users.go, mongodbatlas/x509_authentication_database_users_test.go
The id attribute eas changed to int type due that the MongoDB server returns this value with this type.
=> x509AuthDBUsers: Fixed the id type

mongodbatlas/alert_configurations_test.go, mongodbatlas/api_keys_test.go, mongodbatlas/atlas_users_test.go, mongodbatlas/auditing_test.go, mongodbatlas/cloud_provider_snapshot_restore_jobs_test.go, mongodbatlas/cloud_provider_snapshots_test.go, mongodbatlas/clusters_test.go, mongodbatlas/containers_test.go, mongodbatlas/custom_db_roles_test.go, mongodbatlas/database_users_test.go, mongodbatlas/encryptions_at_rest_test.go, mongodbatlas/global_clusters_test.go, mongodbatlas/maintenance_test.go, mongodbatlas/peers_test.go, mongodbatlas/private_ip_mode_test.go, mongodbatlas/project_api_key_test.go, mongodbatlas/project_ip_whitelist_test.go, mongodbatlas/projects_test.go, mongodbatlas/teams_test.go, mongodbatlas/whitelist_api_keys_test.go
- Prefer deep.Equal over reflect.DeepEqual, some places were doing both some others a mix
- If there's an unexpected error then prefer t.Fatal over t.Error as Fatal will prevent any other case from executing (which would fail anyway)
=> Simplify tests

mongodbatlas/alert_configurations.go
The proper key in the json is lower case, this was probably a typo or copy/paste error
=> Fix incorrect json tag for groupId

mongodbatlas/alert_configurations.go, mongodbatlas/alert_configurations_test.go, mongodbatlas/api_keys.go, mongodbatlas/atlas_users.go, mongodbatlas/auditing.go, mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshots.go, mongodbatlas/clusters.go, mongodbatlas/containers.go, mongodbatlas/custom_db_roles.go, mongodbatlas/database_users.go, mongodbatlas/encryptions_at_rest.go, mongodbatlas/global_clusters.go, mongodbatlas/maintenance.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go, mongodbatlas/peers.go, mongodbatlas/private_endpoints.go, mongodbatlas/private_ip_mode.go, mongodbatlas/project_api_key.go, mongodbatlas/project_ip_whitelist.go, mongodbatlas/projects.go, mongodbatlas/teams.go, mongodbatlas/whitelist_api_keys.go, mongodbatlas/x509_authentication_database_users.go
Making the ServiceOp structs depend on an interfaces enables me to inject my own client for the Ops manager an Cloud manager API
This should be a non breaking change that enables a more flexible extention of the structs
=> Make the ServiceOp depend on an interface

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
- Added field `connectionStrings` for `Cluster` in code and for testing
=> Connection strings

mongodbatlas/alert_configurations.go, mongodbatlas/alert_configurations_test.go
[CLOUDP-59516(https://jira.mongodb.org/browse/CLOUDP-59516)
=> CLOUDP-59516: List available matchers for alerts in the Atlas client

mongodbatlas/global_clusters.go, mongodbatlas/mongodbatlas.go, mongodbatlas/process_measurements.go, mongodbatlas/process_measurements_test.go
[CLOUDP-59968](https://jira.mongodb.org/browse/CLOUDP-59968)
Further comments
```
{
"end": "2020-04-01T12:56:56Z",
"granularity": "PT1M",
"groupId": "5e4e593f70dfbf1010295836",
"hostId": "cluster0-shard-00-00-ajlj3.mongodb-dev.net:27017",
"links": [
{
"rel": "self",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/processes/cluster0-shard-00-00-ajlj3.mongodb-dev.net:27017/measurements?ListOptions=\u0026granularity=PT1M\u0026period=PT1M"
},
{
"rel": "http://mms.mongodb.com/host",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/processes/cluster0-shard-00-00-ajlj3.mongodb-dev.net:27017"
}
],
"measurements": [
{
"dataPoints": [
{
"timestamp": "2020-04-01T12:56:20Z",
"value": null
},
{
"timestamp": …
```
=> CLOUDP-59968: implement list measurements on atlas go client

mongodbatlas/events.go, mongodbatlas/events_test.go, mongodbatlas/mongodbatlas.go
[CLOUDP-57848](https://jira.mongodb.org/browse/CLOUDP-57848)
=> CLOUDP-57848: Implement events resource in the atlas go client

mongodbatlas/mongodbatlas.go, mongodbatlas/process_disk_measurements.go, mongodbatlas/process_disk_measurements_test.go
[CLOUDP-60177](https://jira.mongodb.org/browse/CLOUDP-60177)
Response from the API call:
```
{
"end": "2020-04-06T17:19:48Z",
"granularity": "PT1M",
"groupId": "5e4e593f70dfbf1010295836",
"hostId": "cluster0-shard-00-00-ajlj3.mongodb-dev.net:27017",
"links": [
{
"rel": "self",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/processes/cluster0-shard-00-00-ajlj3.mongodb-dev.net:27017/disks/data/measurements?ListOptions=\u0026granularity=PT1M\u0026period=PT1M"
},
{
"rel": "http://mms.mongodb.com/host",
"href": "https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5e4e593f70dfbf1010295836/processes/cluster0-shard-00-00-ajlj3.mongodb-dev.net:27017"
}
],
"measurements": [
{
"dataPoints": [
{
"timestamp": "2020-04-06T17:19:48Z",
"value": null
}
],
"name": …
```
=> CLOUDP-60177: Implement Get Measurements of a Disk for a MongoDB Process, Atlas

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Added field `private` and `privateSrv` for connection strings
=> Connection strings private

mongodbatlas/logs.go, mongodbatlas/logs_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
[CLOUDP-60178](https://jira.mongodb.org/browse/CLOUDP-60178)
=> CLOUDP-60178: Implement logs API, Atlas

mongodbatlas/process_measurements.go
the `m` param is actually an array so fixing this
=> Make the measurements param an array

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
**Breaking change**
Currently if you want to pause or restart a cluster you can only send the `Paused` property and nothing else or you'll get errors like "Can't pause and update a cluster at the same time"
Having some internal structs as non-pointers were making go serialize them so we could never do this kind of operation
Sadly this may be a breaking change as we are changing the type of the struct and those depending on it may need to update after this change
=> Fix cluster struct to allow pasue/start a cluster

mongodbatlas/atlas_alerts.go, mongodbatlas/atlas_alerts_test.go
[CLOUDP-62220](https://jira.mongodb.org/browse/CLOUDP-62220)
We have recently discovered that the **AcknowledgedUntil** field must be set to null in order to unack an alert. As a result, we decided to make this field a pointer.
=> CLOUDP-62220: Update the AcknowledgedUntil field to be a pointer in the atlas client

mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshot_restore_jobs_test.go
Added new three fields for Snapshot restore jobs called `oplogTs`, `oplogInc` and `pointInTimeUTCSeconds` and its test
=> Three new fields for Snapshot restore jobs options

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Added fields for autoscaling
* Compute
Added a new sruct Compute and its fields
* Enabled
* ScaleDownEnabled
* MinInstanceSize
* MaxInstanceSize
=> Cluster autoscaling compute

mongodbatlas/whitelist_api_keys.go, mongodbatlas/whitelist_api_keys_test.go
https://github.com/mongodb/go-client-mongodb-atlas/issues/95
Support the pagination of [WhitelistAPIKeysService.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#WhitelistAPIKeysService) and [WhitelistAPIKeysServiceOp.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#WhitelistAPIKeysServiceOp.List).
The signature of [WhitelistAPIKeysService.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#WhitelistAPIKeysService) and [WhitelistAPIKeysServiceOp.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#WhitelistAPIKeysServiceOp.List) are changed.
The parameter `listOptions` is added.
=> feat: support the pagination of WhitelistAPIKeysService.List

mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshot_restore_jobs_test.go
https://github.com/mongodb/go-client-mongodb-atlas/issues/95
Support the pagination of [CloudProviderSnapshotRestoreJobsService.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotRestoreJobsService) and [CloudProviderSnapshotRestoreJobsServiceOp.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotRestoreJobsServiceOp.List).
The signature of [CloudProviderSnapshotRestoreJobsService.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotRestoreJobsService) and [CloudProviderSnapshotRestoreJobsServiceOp.List](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotRestoreJobsS …
=> feat: support the pagination at CloudProviderSnapshotRestoreJobsService.List

mongodbatlas/data_lakes.go, mongodbatlas/data_lakes_test.go
This fixes marshalling so that it doesn't serialise an empty json object if some of the flags are not provided.
https://github.com/mongodb/mongocli/pull/240
=> CLOUDP-66612: fix json marshaling

githooks/pre-commit, mongodbatlas/mongodbatlas.go, mongodbatlas/search.go, mongodbatlas/search_test.go
=> CLOUDP-67056: Implement search API in the go client

mongodbatlas/database_users.go, mongodbatlas/database_users_test.go
Added a field for database user called `AWSIAMType` and its test.
=> Added field for aws iam type for database user

mongodbatlas/search.go
There are more properties to a search field than fully documented on the API
=> fix: add more fields to the search field

mongodbatlas/database_users.go, mongodbatlas/database_users_test.go
Adds support for scoping db users to a particular cluster or data lake
=> feature: add scope support for db users

mongodbatlas/projects.go, mongodbatlas/projects_test.go
Adding API call to [Remove One User from a Project](https://docs.atlas.mongodb.com/reference/api/project-remove-user/) that we need to implement the mongocli command `mongocli iam projects user(s) delete|rm`
=> CLOUDP-70755: Add DELETE /groups/{GROUP-ID}/users/{USER-ID} to atlas go client

.travis.yml, README.md, go.mod
Go 1.15 was released the other day, we are adding support on our testing and I'm also proposing we follow a similar approach to go where they only support the last two major releases
=> chore: update supported go versions

mongodbatlas/mongodbatlas.go, mongodbatlas/third_party_integration.go, mongodbatlas/third_party_integration_test.go
Implemented [Third-Party Integration Settings](https://docs.atlas.mongodb.com/reference/api/third-party-integration-settings/)
=> CLOUDP-70872: Adding Third-Party Integration Settings

mongodbatlas/ldap_configurations.go, mongodbatlas/ldap_configurations_test.go
I discovered bugs in the implementation of the LDAP configuration api call https://github.com/mongodb/go-client-mongodb-atlas/pull/135#pullrequestreview-486081262 https://github.com/mongodb/go-client-mongodb-atlas/commit/346af62096340db047f8b37362d1b886868f454d:
1. `LDAPConfigurationsService.Save`  was using the struct `LDAP` instead of `LDAPConfiguration`
2. The path of the `LDAPConfigurationsService.Delete` was not correct
=> CLOUDP-72727: Fix LDAPConfigurationsService.Save to pass LDAPConfiguration as input

mongodbatlas/database_users.go
This small fix is related to https://github.com/mongodb/terraform-provider-mongodbatlas/issues/292
just extracting the **auth** db name in case of update minimal change. 
Tested locally (custom build) before updating the reference in the terraform repo 
```
leofigy@DESKTOP-IQOJR0Q:~/mongo/staging> terraform apply
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "mongodbatlas_database_user" "atlasexternal" {
+ auth_database_name = "$external"
+ aws_iam_type       = "NONE"
+ id                 = (known after apply)
+ project_id         = "REDACTED"
+ username           = "C=US,ST=California,L=CITY,O=COMPANY,OU=UNIT,CN=sampleuserX"
+ x509_type          = …
```
=> Setting the right auth db name 

mongodbatlas/performance_advisor.go, mongodbatlas/performance_advisor_test.go
We got a deserialization error during the implementation of the suggestedIndex command on mongocli due to the field `Predicates` inside the struct`Operation`
=> CLOUDP-73368: fixing the Operation struct in the atlas go client

mongodbatlas/mongodbatlas_test.go, mongodbatlas/organizations.go, mongodbatlas/organizations_test.go
Addresses #143 
The Ops Manager and Atlas API supports filtering Organization list results by the name, however this Go client does not support that at the moment. This PR would add that functionality and adds a test to help ensure it works.
I recognize this is a breaking change to the interface so I'm open to discussion on a better way to do it. Though I saw this pattern in `ContainersListOptions` which is where I adopted it from.
https://github.com/mongodb/go-client-mongodb-atlas/blob/d1f10b2b037bf8a783bada68f9c40f9d56a05a1f/mongodbatlas/containers.go#L30-L33
=> add OrganizationsListOptions for filtering organization list results

mongodbatlas/alert_configurations.go
This is to fix for the case where the threshold is equal to 0 https://github.com/mongodb/terraform-provider-mongodbatlas/issues/311. that gets ignored when bypassing to the client.
- [] I have run `make fmt` and formatted my code
=> letting 0 be as value in the threshold

mongodbatlas/processes.go, mongodbatlas/processes_test.go
The Atlas API has support for returning the `userAlias` as part of the response body for listing all the processes under a project.
Documentation reference: https://docs.atlas.mongodb.com/reference/api/processes-get-all/
This PR makes sure that field is returned as part of the processes `List` function.
=> NOREF: Include userAlias for processes

mongodbatlas/mongodbatlas.go
Add Raw field in response to be able to store raw data from atlas server response
=> Add Raw field to atlas response

mongodbatlas/cloud_provider_access.go, mongodbatlas/cloud_provider_access_test.go
Hi @gssbzn 
This is done as part of the terraform integration, the case is the following , in terraform one can create the roles, and then apply a destroy , so the delete operation must be idempontent, but using the existing url it fails telling you that the DELETE operation is not valid 
```
2020/11/22 21:48:27 [DEBUG] mongodbatlas_cloud_provider_access.first: applying the planned Delete change
mongodbatlas_cloud_provider_access.first: Destroying... [id=aWQ=:NWZiYjMwYmVkYTU3ZDQxMTdiMmFhNWVm-cHJvamVjdF9pZA==:NWNmNWE0NWE5Y2NmNjQwMGU2MDk4MWI2-cHJvdmlkZXJfbmFtZQ==:QVdT]
2020-11-22T21:48:27.534-0600 [DEBUG] plugin.terraform-provider-mongodbatlas_v0.8.0.exe: 2020/11/22 21:48:27 [DEBUG] MongoDB Atlas API Request Details:
2020-11-22T21:48:27.534-0600 [DEBUG] …
```
=> Provider access integration

mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
Link to any related issue(s): https://jira.mongodb.org/browse/CLOUDP-78002
This is a fix adding the support for `errorCode` (https://docs.atlas.mongodb.com/reference/api/api-errors/).
**Important!** This is a breaking change as changes the type of the field `ErrorCode` from `int` to `string` and all the clients will have to change their codebase after using the new version of the library. This needs to be mentioned in the release notes.
(as discussed with the team we can afford to break this as the main clients don't use this object much - but will appreciate the alternative opinions)
=> CLOUDP-78002: adds support for Atlas Error codes

mongodbatlas/mongodbatlas.go
Bringing this from the ops manager client, in some cases we some extra bytes may be left in the body, this way we make sure to read it all so the connection can be reused
=> fix: improve connection closing

mongodbatlas/database_users.go, mongodbatlas/database_users_test.go
Delete the omitempty for scopes parameter so it can send an empty array of scopes in json request.
=> INTMDB-144: deleted omitempty for scopes of database users

mongodbatlas/cloud_provider_snapshot_restore_jobs.go
I noticed that this link was broken. Changed to be the same format as other API links in the documentation & verified it goes to the correct documentation page.
This seems to be the only such broken link in documentation for these interfaces.
=> Fix broken link in api documentation for CloudProviderSnapshotRestoreJobsService.

mongodbatlas/mongodbatlas.go
I'm planning a bit of a refactor on how we set up our client in the cli and this helper would be useful
=> Add a helper method to group client options

mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_test.go
add Regionalized Private Endpoint Status to atlas go client
- https://docs.atlas.mongodb.com/reference/api/private-endpoints-update-regional-mode
- https://docs.atlas.mongodb.com/reference/api/private-endpoints-get-regional-mode
=> CLOUDP-81043: add Regionalized Private Endpoint Status to atlas go client

mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_test.go
[Get one private endpoint](https://docs.atlas.mongodb.com/reference/api/private-endpoints-endpoint-get-one) needs url encoding for `ENDPOINT-ID` when used with azure.
[Delete one private endpoint](https://docs.atlas.mongodb.com/reference/api/private-endpoints-endpoint-delete-one) needs url encoding for `ENDPOINT-ID` when used with azure.
Tested with mongocli
```
./bin/mongocli atlas privateendpoint azure interface describe 6009a7a62cde816e1914b656 --privateEndpointId /subscriptions/19265c27-b60e-4c3b-9426-ae3f507300b5/resourceGroups/test/providers/Microsoft.Network/privateEndpoints/test
ID                                                                                                                          IP ADDRESS   STATUS   ERROR …
```
=> INTMDB-167: URL encode private enpoint ID

mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshot_restore_jobs_test.go
Adds the Components array to the struct `CloudProviderSnapshotRestoreJob`.
Link to any related issue(s): #171
=> Add support for components in `CloudProviderSnapshotRestoreJob`

CODE_OF_CONDUCT.md, CONTRIBUTING.md
Checking for a contribution in the ops manager client I saw the OM version of this page was really outdated and for atlas was the same
=> docs: update contributing guidelines

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
This PR adds support for https://docs.atlas.mongodb.com/reference/api/clusters-check-operation-status/ endpoint to clusters.
=> CLOUDP-83026: support for cluster status endpoint

mongodbatlas/cloud_provider_regions.go, mongodbatlas/cloud_provider_regions_test.go, mongodbatlas/mongodbatlas.go
I have added the service to handle the endpoint `GET /api/atlas/v1.0/groups/{GROUP-ID}/clusters/provider/regions`
=> CLOUDP-85749: Add new available region endpoint to the atlas go client

mongodbatlas/ip_info.go, mongodbatlas/ip_info_test.go, mongodbatlas/mongodbatlas.go
I have added the service to handle the endpoint `GET api/private/ipinfo`
=> CLOUDP-85933: Add service to get the public ip to the atlas go client

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
=> CLOUDP-86937: Add support to the Atlas Go Client to load sample data into a cluster

mongodbatlas/alert_configurations.go, mongodbatlas/api_keys.go, mongodbatlas/auditing.go, mongodbatlas/checkpoints.go, mongodbatlas/cloud_provider_regions.go, mongodbatlas/cloud_provider_snapshot_backup_policies.go, mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshots.go, mongodbatlas/custom_db_roles.go, mongodbatlas/data_lakes.go, mongodbatlas/database_users.go, mongodbatlas/encryptions_at_rest.go, mongodbatlas/events.go, mongodbatlas/global_clusters.go, mongodbatlas/logs.go, mongodbatlas/maintenance.go, mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_deprecated.go, mongodbatlas/private_ip_mode.go, mongodbatlas/process_database_measurements.go, mongodbatlas/process_disk_measurements.go, mongodbatlas/process_disks.go, mongodbatlas/process_measurements.go, mongodbatlas/project_api_key.go, mongodbatlas/project_ip_whitelist.go, mongodbatlas/teams.go, mongodbatlas/whitelist_api_keys.go, mongodbatlas/x509_authentication_database_users.go
We've known for a while that many of our godocs were rendering improperly given space and new line issues, see [mongodbatlas#APIKeysServiceOp.Update](https://pkg.go.dev/go.mongodb.org/atlas@v0.7.2/mongodbatlas#APIKeysServiceOp.Update) for example and compare with the next method
I had some time today and went and fixed all our docs
=> docs: fix godoc rendering

mongodbatlas/database_users.go
Link to any related issue(s): #189
=> fix: fix username path escape for db username

.github/workflows/pr.yml, .golangci.yml, GNUmakefile, mongodbatlas/cloud_provider_snapshot_restore_jobs.go
Update golangci and enable a new linter for json tags, this may be handy to prevent copy past errors, we had those before and it caught one on the ops manager version of this lib
=> feat: update golancgci and enable tagliatelle

mongodbatlas/online_archives.go, mongodbatlas/online_archives_test.go
Hello @gssbzn , @andreaangiolillo , adding missing attributes required to do a custom type archive log.
- added the query parameter in criteria
- changed from float64 to *float64 to avoid sending  expireAfterDays when it's `custom` type.
```
│ Error: error creating MongoDB Atlas Online Archive:: POST https://cloud.mongodb.com/api/atlas/v1.0/groups/5cf5a45a9ccf6400e60981b6/clusters/test-angel-cloud-backup1/onlineArchives: 400 (request "INVALID_ATTRIBUTE") Invalid attribute expireAfterDays specified.
│
│   with mongodbatlas_online_archive.users_archive_query,
│   on main.tf line 25, in resource "mongodbatlas_online_archive" "users_archive_query":
│   25: resource "mongodbatlas_online_archive" "users_archive_query" {
```
required in …
=> Adding missing args to do a custom online archive

.golangci.yml, mongodbatlas/cloud_provider_access.go, mongodbatlas/clusters.go, mongodbatlas/ip_info.go, mongodbatlas/mongodbatlas.go
`golint` has been archived and it's now deprecated on golangci-lint, they recommend to replace with revive
=> lint: replace golint with revive

mongodbatlas/search.go, mongodbatlas/search_test.go
Added properties to search index and search analyzer struct in order to complain with the current mongodb atlas API documentation
=> INTMDB-17: Update search

.golangci.yml, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
Enables `thelper`, this linter makes sure that test helper functions call `t.Helper`
Enables `errorlint`, making sure error handling follow go1.13 error handling best practices
=> task: enable thelper and errorlint

mongodbatlas/search.go
Added structs to manage custom analyzers in index struct, also documentation was added to code
INTMDB-17
- [ x] New feature (non-breaking change which adds functionality)
=> added custom analyzer structs

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go
Renamed AdvancedRegionSpec to AdvancedReplicationSpec and added missing json string for `RegionConfigs`
=> Renamed AdvancedRegionSpec to AdvancedReplicationSpec

mongodbatlas/organization_invitations.go, mongodbatlas/organization_invitations_test.go, mongodbatlas/organizations.go, mongodbatlas/project_invitations.go, mongodbatlas/project_invitations_test.go, mongodbatlas/projects.go
Bug: The Request Body Parameters `ID`, `OrgID`, `GroupID` must be blank when using `POST`, `PATCH` endpoints
=> Fixed Invite New User endpoints for organizations and projects

mongodbatlas/accesslist_api_keys.go, mongodbatlas/clusters.go, mongodbatlas/mongodbatlas.go, mongodbatlas/serverless_instances.go, mongodbatlas/serverless_instances_test.go
Jira Ticket: [CLOUDP-96138](https://jira.mongodb.org/browse/CLOUDP-96138)
=> CLOUDP-96138: Add serverless to the atlas go client

mongodbatlas/maintenance.go, mongodbatlas/maintenance_test.go
This PR includes the AutoDefer method to automatically defer any maintenance as explained here https://docs.atlas.mongodb.com/reference/api/maintenance-window-auto-defer/
=> Adding AutoDefer method to automatically defer any maintenance

mongodbatlas/access_tracking.go, mongodbatlas/access_tracking_test.go, mongodbatlas/mongodbatlas.go
add [access tracking](https://docs.atlas.mongodb.com/reference/api/access-tracking/) to the atlas go client
=> CLOUDP-97443: add access tracking to the atlas go client

mongodbatlas/projects.go
=> feat: add support for creation of cloudgov only projects

mongodbatlas/maintenance.go
`AutoDeferOnceEnabled` property was added to `MaintenanceWindow` struct, just to be on sync with the atlas api (https://docs.atlas.mongodb.com/reference/api/maintenance-windows-view-in-one-project/)
Link to any related issue(s): INTMDB-230
=> INTMDB-230: Added autoDeferOnceEnabled property to MaintenanceWindow struct

mongodbatlas/mongodbatlas.go, mongodbatlas/service_version.go, mongodbatlas/service_version_test.go
Parse service version header `X-MongoDB-Service-Version`
Link to any related issue(s): [CLOUDP-82836](https://jira.mongodb.org/browse/CLOUDP-82836)
=> CLOUDP-82836: Parse service version

mongodbatlas/projects.go, mongodbatlas/projects_test.go
[CLOUDP-95603: [Mongocli - Atlas] Add support for projectOwnerId flag with project creation/modification](https://jira.mongodb.org/browse/CLOUDP-95603)
Description:
Added query param [projectOwnerId](https://docs.atlas.mongodb.com/reference/api/project-create-one/#request-query-parameters) to `Projects.Create`
=> Adding projectOwnerId to Projects.Create

mongodbatlas/performance_advisor.go, mongodbatlas/performance_advisor_test.go
I have added the following performance advisor endpoints:
- [Enable Managed Slow Operation Threshold](https://docs.atlas.mongodb.com/reference/api/pa-managed-slow-ms-enable/)
- [Disable Managed Slow Operation Threshold](https://docs.atlas.mongodb.com/reference/api/pa-managed-slow-ms-disable/)
=> CLOUDP-97442: update performance advisor with new endpoints -> atlas go client

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
- Added two parameters `defaultReadConcern` and `defaultWriteConcern` for process args
=> INTMDB-252: Added two parameters for Process args

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go
- Added parameter `VersionReleaseSystem` for advanced cluster
=> INTMDB-216: Added parameter version release system for advanced cluster

mongodbatlas/projects.go, mongodbatlas/projects_test.go
Added a new property `withDefaultAlertsSettings` to `Project` struct to enable/disable default settings on create project
Link to any related issue(s): [INTMDB-270](https://jira.mongodb.org/browse/INTMDB-270)
=> INTMDB-270: Added  'withDefaultAlertsSettings' property to Project struct

mongodbatlas/convert.go, mongodbatlas/custom_db_roles.go, mongodbatlas/custom_db_roles_test.go
Fixes https://github.com/mongodb/go-client-mongodb-atlas/issues/263
Just posting this here to streamline any fix on this. If further doc/tests/etc. are needed let me know. Didn't want to run the tests in case they were integration and not just unit tests.
I did use a `replace` in the `go.mod` to use my fork and this fixes my issue, but you have to wrap all strings as pointers. Therefore, this is a breaking change.
=> custom_db_role resource use *string

.github/workflows/release-check.yml
The post tag checks are failing, ubuntu may be using an old version of go
=> fix: fixes release smoke tests

mongodbatlas/alert_configurations.go
Added new parameter `teamName` for alert configurations
=> INTMDB-5: added parameter team name for alert configurations

auth/device_flow.go, auth/device_flow_test.go, auth/oauth_test.go
Adds a method to revoke access or refresh tokens
=> feat: add the ability to revoke tokens

auth/device_flow.go, auth/device_flow_test.go
Add a method to refresh tokens
Also rename the revoke method to make it consistent with other methods that include the word `Token`
=> feat: add the ability to refresh tokens

mongodbatlas/cloud_provider_snapshot_export_buckets.go, mongodbatlas/cloud_provider_snapshot_export_buckets_test.go, mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshot_restore_jobs_test.go, mongodbatlas/cloud_provider_snapshots.go, mongodbatlas/mongodbatlas.go
Added snapshot export buckets support
Link to any related issue(s): [INTMDB-299](https://jira.mongodb.org/browse/INTMDB-299)
=> INTMDB-299: Added snapshot export bucket support

mongodbatlas/cloud_provider_snapshot_export_jobs.go, mongodbatlas/cloud_provider_snapshot_export_jobs_test.go, mongodbatlas/mongodbatlas.go
Added support for `CloudProviderSnapshotExportJobs`
Link to any related issue(s): [INTMDB-299](https://jira.mongodb.org/browse/INTMDB-299)
=> INTMDB-299: Added snapshot export jobs support

mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
This PR adds an ability for the `Client` to automatically add trailing slash (`/`) to the end of the provided URL. The motivation behind this is that some internal tools use this library and it is easier to assume that the library handles both cases: with, and without trailing slash.
cc: @jamesbroadhead 
Link to any related issue(s): https://jira.mongodb.org/browse/CLOUDP-114669
=> CLOUDP-114669: Automatically add trailing slash to the URL

mongodbatlas/third_party_integration.go, mongodbatlas/third_party_integration_test.go
Feature Add: Prometheus and Microsoft Team to the Third Party Integration Settings
=> INTMDB-311: Feature Add: Prometheus and Microsoft Team to the Third Party Integration Settings

mongodbatlas/project_settings.go, mongodbatlas/project_settings_test.go, mongodbatlas/projects.go
Atlas customers can now manage project settings and all cluster resizing via the Admin API, rather than shifting to the UI for certain operations. This improves operational workflows, allowing customers to manage their deployments more programmatically.
[Get Product Settings](https://www.mongodb.com/docs/atlas/reference/api/project-settings-get-one/), [Update Project Settings](https://www.mongodb.com/docs/atlas/reference/api/project-settings-update-one/)
=> CLOUDP-118028: [atlascli] Allow to list and edit project settings

mongodbatlas/x509_authentication_database_users.go, mongodbatlas/x509_authentication_database_users_test.go
=> feat: add pagination to listing x509 users

auth/oauth.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
We are adding a `WithRaw()` option to allow copying body responses.
based on https://github.com/mongodb/go-client-mongodb-ops-manager/pull/72
=> CLOUDP-110989: Capture Raw response body

auth/oauth.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
Added a `OnResponseProcessed` for logging purposes
Link to any related issue(s): [CLOUDP-110989](https://jira.mongodb.org/browse/CLOUDP-110989)
=> CLOUDP-110989: Adds OnResponseProcessed

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
I added "Upgrade One Shared Tier Cluster" endpoint to Atlas Go Client, and a test to check the correctness of the implementation. 
After creating a cluster that we want to upgrade, the upgrade request should be sent to the following endpoint: `https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/{GROUP-ID}/clusters/tenantUpgrade`. In the body of the request, there should be an upgraded cluster object. Example body:
```
{
"name": "tenantCluster",
"diskSizeGB": 100,
"numShards": 1,
"providerSettings": {
"providerName": "AWS",
"instanceSizeName": "M40",
"regionName": "US_EAST_1"
},
"clusterType" : "REPLICASET",
"replicationFactor": 3,
"replicationSpecs": [{
"numShards": 1,
"regionsConfig": {
"US_EAST_1": {
"analyticsNodes": 0,
"electableNodes": 3,
"priority": 7,
"readOnlyNodes": 0
}
}, …
```
=> CLOUDP-126267: Add 'Upgrade One Shared Tier Cluster' endpoint to atlas go client

mongodbatlas/organizations.go, mongodbatlas/organizations_test.go
Add filter by name on list all groups by org
Link to any related issue(s): CLOUDP-127482
=> CLOUDP-127482: Add filter by name on list all groups by org

mongodbatlas/teams.go
The parameter orgID in the UpdateTeamRoles should be groupID as it's modifying team roles in a specific project.
Link to any related issue(s): https://github.com/mongodb/go-client-mongodb-atlas/issues/303
=> Fix: Fixed naming of parameter in UpdateTeamRoles

mongodbatlas/advanced_clusters.go
Ticket: [CLOUDP-132967](https://jira.mongodb.org/browse/CLOUDP-132967)
I have tested that my changes work  as expected:
```
./bin/atlas cluster create test1 --file ~/cluster.yaml -o json                                  
{
"backupEnabled": false,
"biConnector": {
"enabled": false,
"readPreference": "secondary"
},
"clusterType": "REPLICASET",
"connectionStrings": {},
"diskSizeGB": 40,
"encryptionAtRestProvider": "NONE",
"groupId": "5e4e593f70dfbf1010295836",
"id": "62fb443c882d5d628508c0ec",
"labels": [
{
"key": "Infrastructure Tool",
"value": "mongoCLI"
}
],
"mongoDBMajorVersion": "5.0",
"mongoDBVersion": "5.0.10",
"name": "test1",
"paused": false,
"pitEnabled": false,
"stateName": "CREATING",
"replicationSpecs": [
{
"numShards": 1,
"id": "62fb443c882d5d628508c0e5",
"zoneName": "Zone 1", …
```
=> CLOUDP-132967: add the ability to use yaml file for advance cluster

.github/workflows/pr.yml, .github/workflows/release-check.yml, .golangci.yml, GNUmakefile, auth/doc.go, go.mod, mongodbatlas/advanced_clusters.go, mongodbatlas/doc.go, mongodbatlas/ip_info_test.go
=> Update to Go v1.18

mongodbatlas/processes.go, mongodbatlas/processes_test.go
Add support for GETing a single process 
=> feat: add GET process

mongodbatlas/advanced_clusters.go, mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
The ProcessArgs is missing `OplogMinRetentionHours` property. See [Update Advanced Configuration Options for One Cluster](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#operation/upgradeOneTenantCluster)
=> CLOUDP-139997: added OplogMinRetentionHours to ProcessArgs

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
The cluster struct is missing  the `RootCertType` parameter. ([API](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#operation/createOneCluster))
=> CLOUDP-141434: Add RootCertType to the atlas go client

.github/workflows/pr.yml
Drops support for go1.17, this is inline with our support policy we kept it because it wasn't affecting us but it now block updating a test lib which requires 1.18+
=> task: drop support for 1.17

mongodbatlas/cloud_provider_snapshot_export_jobs.go
Updated backup export jobs to take jobId flag as opposed to bucketId
=> CLOUDP-149874: export jobs should use exportJobID

mongodbatlas/cloud_provider_snapshot_export_jobs.go, mongodbatlas/cloud_provider_snapshot_export_jobs_test.go
_Jira ticket:_  [CLOUDP-149874](https://jira.mongodb.org/browse/CLOUDP-149874)
Updated `exportJobId` to `exportId` based on [this comment](https://github.com/mongodb/mongodb-atlas-cli/pull/1558#pullrequestreview-1219897594) and the appropriate docs
> Thanks for this work! I think you referenced our deprecated API docs for the copy (we're taking these down soon!) and so I've updated the descriptions to match the [OpenAPI generated ones](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Cloud-Backup-Export/operation/returnOneCloudBackupSnapshotExportJob).
> With that in mind, do you think the flag name should be exportId instead of exportJobId to match the API parameter in the docs?
=> CLOUDP-149874: export jobs should use exportID as per docs

mongodbatlas/mongodbatlas.go, mongodbatlas/root.go, mongodbatlas/root_test.go
INTMDB-454: Add support for root query to get org_id from API Key used in Terraform
=> INTMDB-454: Add support for root query to get org_id from API Key used in Terraform

mongodbatlas/cloud_provider_snapshot_backup_policies.go
Empty struct to delete backup distribution configuration
Need a way to emit empty copySettings array this to PATCH API call to remove distribution configuration
```
{
"clusterId":"63a32ba4zzz3dcaa7eaf",
"clusterName":"test-backups",
"copySettings":[]
}
```
=> INTMDB-400: Empty struct to delete backup distribution configuration

mongodbatlas/ldap_configurations.go, mongodbatlas/ldap_configurations_test.go
Fixes #339 
This will be a breaking change but it's necessary to correct the reported issue
=> fix: fixes ldap config to allow PATCH

mongodbatlas/advanced_clusters_test.go, mongodbatlas/alert_configurations_test.go, mongodbatlas/alerts_test.go, mongodbatlas/cloud_provider_snapshot_backup_policies_test.go, mongodbatlas/cloud_provider_snapshot_export_buckets_test.go, mongodbatlas/cloud_provider_snapshot_export_jobs_test.go, mongodbatlas/clusters_test.go, mongodbatlas/performance_advisor_test.go, mongodbatlas/serverless_instances_test.go
Small clean up to remove some variables that shadow some global consts that should be equivalent
=> test: clean up shadow variables for constants

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
Release preparation to make outage simulation and test failover available
=> task: release 0.22.0 preparation

v2/api/atlas_client.go, v2/tools/config/go-templates/atlas_client.mustache, v2/tools/scripts/generate.sh
Use env var provided version when running generator job.
To fully automate generation we need to supply all input arguments from CI/CD job.
The current version matches the proposal in the specification and it is likely to change.
=> CLOUDP-155226: include versioned API version in requests

.gitignore, GNUmakefile, tools/Makefile, tools/package-lock.json
We should use a single call (make, etc.) for each SDK repository as a standard.
This PR introduces:
```
make openapi-pipeline
```
target that can be triggered to perform end to end open API generation and validation.
=> CLOUDP-155911: unify make calls

mongodbatlas/organizations.go, mongodbatlas/organizations_test.go
=> feat: add org creation endpoint

mongodbatlas/organizations.go
After some manual QA the ownerID needs to be a pointer or it will fail when using OAuth as auth mechnism
=> fix: make org owner optional

.github/workflows/tools.yaml, GNUmakefile, api/test/regression/multi_cloud_clusters.go, api/v1alpha/README.md, tools/Makefile, tools/README.md, tools/config/go-templates/README.mustache
Changes
- linting - generally templates proving our ability for passing lint errors,
- compatibility tests - used for tooling but will be breaking/blocking jobs when a new version of that API is introduced.
=> CLOUDP-163493 - ci/cd cleanup

tools/package-lock.json, tools/package.json, tools/transformer/README.md, tools/transformer/__tests__/transformations.test.js, tools/transformer/src/apifile.js, tools/transformer/src/transform.js, tools/transformer/src/transformations.js
Required fixes in the transformer before we start adding linting and flagging invalid cases:
- Minimize logging for end users (do not run debug or trace commands) so output of the transformer can be used to figure out what is wrong with the openapi. Warn will be default. 
- Add abstraction for file storage (so we can introduce more ways we read and store openapi file - it will enable us to use transformer as validator case.)
Done `make transform_openapi`
We now only see ERRORS and WARNINGS. Some of the warnings will be downgraded to info/
=> CLOUDP-165150: Reduce logging for CI/CD and validation purposes.

.github/workflows/autoupdate-dev.yaml
API preview url might change a lot so decided to use the secret to expose it. 
I have tried to reuse the existing workflow but with a number of changes, it seems like a copy of the production one is much easier.
To reduce noise workflow is run on demand but it can be changed to a cron job as well. 
Secret created:
=> CLOUDP-155910: add ability to generate client from api preview

.github/workflows/autoupdate-dev.yaml, .github/workflows/autoupdate-master.yaml
I have found that we have 3 duplicated workflows names between sdkv2 and master. This PR renames workflows to make it clear which one is which. Once we select workflow we see workflow file but it is better to make it clear in the workflow list as well.
=> chore: rename master workflow

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
CLOUDP-167925: add support for PrivateEndpoint.srvShardOptimizedConnectionString
https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Multi-Cloud-Clusters/operation/getCluster (see response samples connectionStrings.privateEndpoint)
=> CLOUDP-167925: add support for PrivateEndpoint.srvShardOptimizedConnectionString

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> CLOUDP-167925: 0.23.2 prep

.github/workflows/autoupdate-master.yaml
This change will allow us to not rely on the schedule and dispatch autoupdates multiple times a day manually or by bot trigger.
=> fix: add way to manually dispatch master branch

mongodbatlas/online_archives.go, mongodbatlas/online_archives_test.go
Add CollectionType support to online archive
https://github.com/mongodb/terraform-provider-mongodbatlas/issues/1081
=> INTMDB-648: Add CollectionType support

mongodbatlasv2/model_error.go, openapi/atlas-api-transformed.yaml, tools/transformer/src/atlasTransformations.js
CLOUDP-168427
Temp workaround that will enable us to process errors in the GO SDK. 
Actuall fix made in the openapi.
=> CLOUDP-168427: remove parameters from the Error object

mongodbatlas/database_users.go
As per the old docs:
> AWS IAM usernames include characters which must be URL encoded.
> Replace all : characters with %3A.
> Replace all / characters with %2F.
https://www.mongodb.com/docs/atlas/reference/api/database-users-get-single-user/#example-request
Using `url.PathEscape` would only encode `/` characters, while `url.QueryEscape` encode both `:` and `/`
Link to any related issue(s): https://github.com/mongodb/mongodb-atlas-cli/issues/1817
=> CLOUDP-169104: Fix encoding for AWS IAM usernames

mongodbatlas/backup_compliance_policy.go, mongodbatlas/backup_compliance_policy_test.go, mongodbatlas/mongodbatlas.go
New Feature: Backup Compliance Policy Support
=> INTMDB-587: New Feature: Backup Compliance Policy Support

mongodbatlas/project_settings.go, mongodbatlas/project_settings_test.go
Added IsExtendedStorageSizesEnabled to ProjectSettings
Part of INTMDB-466
=> INTMDB-466: Added IsExtendedStorageSizesEnabled to ProjectSettings

mongodbatlas/database_users.go
This reverts commit 056a7562abcd0ef7ac75fff5f1a924dc4dc51460.
The root cause was query encoding occurring on the CLI and the SDK, so this change was not required 
Keeping PathEscape for consistency across the API and v2sdk as it works as expected
https://github.com/mongodb/mongodb-atlas-cli/issues/1817
=> Revert "CLOUDP-169104: Fix encoding for AWS IAM usernames (#452)"

tools/Makefile, tools/scripts/generate.sh
Nit: OpenAPI file env var is not taken into account and not needed when calling generate. 
Found out during investigation of the evergreen issues
=> CLOUDP-175206: remove openapi file override

GNUmakefile, test/client_test.go
Example application is subject to be broken when a new Resource version of the API will be introduced that changes the resources it uses. That is fine for us as then update PRs will fail and will require manual correction (which we want).
However, example applications were also used as tests for CI/CD processes which is not desired breaking changes will also break the job.  This PR improves the openapi pipeline to rely on client test (it will compile entire client codebase by running the test).
```
make openapi_pipeline
```
Running tests with broken codebase:
```
mongodbatlasv2/api_clusters.go:87:36: undefined: CloudProviderRegionsApi
FAIL    go.mongodb.org/atlas/test [build failed]
FAIL
```
=> CLOUDP-175598: openapi pipeline to run client test

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
Releasing new version of Atlas go-client to support fix for [INTMDB-809](https://jira.mongodb.org/browse/INTMDB-809) ([#465](https://github.com/mongodb/go-client-mongodb-atlas/pull/465) is the main fix) and adding support for Data Federation.
=> INTMDB-813: 0.26.0 pre-release

mongodbatlas/data_federation.go, mongodbatlas/data_federation_test.go
Follow-up PR of #475. Adding Hostanames and State fields to Data Federation.
=> INTMDB-801: Add State and Hostnames fields to Data Federation

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> INTMDB-825: 0.26.1 pre-release

mongodbatlas/data_federation.go, mongodbatlas/data_federation_test.go
Add Data Federation Query Limit to go-client.
Link to any related issue(s): [INTMDB-802](https://jira.mongodb.org/browse/INTMDB-802)
=> INTMDB-802: Add Data Federation Query Limit

mongodbatlas/data_lakes_pipeline.go
This PR is a follow-up of #482. Making some fixes after testing the resource with terraform
=> INTMDB-804: struct fixes

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Adding tags to the clusters APIs.
Context, we are changing this here given clusters is still being changed to SDKv2, so while it stays on SDKv1 we have to make this change here.
=> CLOUDP-179698 Add tags to clusters

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go
Adding tags to the advanced clusters APIs.
followup from https://github.com/mongodb/go-client-mongodb-atlas/pull/488
=> CLOUDP-179698 Add tags to advanced clusters

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
Releasing new version of Atlas go-client adding support for cluster tagging.
=> CLOUDP-179714: 0.27.0 pre-release

mongodbatlas/serverless_instances.go, mongodbatlas/serverless_instances_test.go
Add tags field to serverless apis
followup from https://github.com/mongodb/go-client-mongodb-atlas/pull/489
=> CLOUDP-179698 Add tags to serverless

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
Releasing SDK to contain tags field on serverless instances apis
=> CLOUDP-179719 v0.28.0 pre-release

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go, mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
This PR adds support for the query param `retainBackups` in cluster and advance cluster
=> INTMDB-781: Query Parameter Add: retainBackups in Cluster and Advanced_Cluster

mongodbatlas/organizations.go, mongodbatlas/organizations_test.go
This PR adds the [renameOrganization](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Organizations/operation/renameOrganization) supports to organization.
=> INTMDB-860: [GO SDK] Add missing endpoint to organization resource

mongodbatlas/cloud_provider_access.go, mongodbatlas/cloud_provider_access_test.go
This PR adds GetRole to CloudProviderAccessService
Ticket: [CLOUDP-78160](https://jira.mongodb.org/browse/CLOUDP-78160)
=> INTMDB-137: Add Get Role to CloudProviderAccessService

mongodbatlas/cloud_provider_access.go, mongodbatlas/cloud_provider_access_test.go
`CloudProviderAccessService.GetRole` returns `AWSIAMRole` instead of an array as the [Open API spec suggests](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Cloud-Provider-Access/operation/deauthorizeCloudProviderAccessRole). Fixing the Open API spec in [#76871](https://github.com/10gen/mms/pull/76871)
=> INTMDB-137: Fix output of CloudProviderAccessService.GetRole

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
This PR adds support `transactionLifetimeLimitSeconds` parameter for `ProcessArgs`. This param was added in [CLOUDP-183132](https://jira.mongodb.org/browse/CLOUDP-183132)
Link to any related issue(s): [INTMDB-874](https://jira.mongodb.org/browse/INTMDB-874)
=> INTMDB-874:  Support transactionLifetimeLimitSeconds parameter in Cluster and Advanced Cluser

README.md
Since we have other SDK in GA state we need to flag in the old repository. 
Putting a message into Readme.md will be good start.
This PR needs docs review
=> CLOUDP-185079: notify users about new SDK

mongodbatlas/organizations.go, mongodbatlas/organizations_test.go
This PR adds `FederationSettingsId` to the org service. [Create Organizations](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Organizations/operation/createOrganization) 
=> INTMDB-838: Add FederationSettingsId to org

mongodbatlas/projects.go, mongodbatlas/projects_test.go
This PR adds the [update endpoint](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Projects/operation/updateProject) to the project service.
=> INTMDB-914: Add update to project

mongodbatlas/cloud_provider_access.go, mongodbatlas/cloud_provider_access_test.go
Ticket: [INTMDB-545](https://jira.mongodb.org/browse/INTMDB-545)
This PR adds Azure support to cloudProviderAccess.
**BREAKING CHANGE**: Renamed `AWSIAMRole` to `IAMRole`
=> INTMDB-545!: add Azure support to cloudProviderAccess

mongodbatlas/cloud_provider_access.go, mongodbatlas/cloud_provider_access_test.go
Ticket: [INTMDB-545](https://jira.mongodb.org/browse/INTMDB-545)
This PR updates `CloudProviderAccessService` to support Azure.
=> INTMDB-545: Update CloudProviderAccessService to support azure

.github_changelog_generator, CHANGELOG.md, RELEASING.md, mongodbatlas/mongodbatlas.go
=> fix: release bump for the SDK

mongodbatlas/database_users.go, mongodbatlas/database_users_test.go
This PR adds support for `OIDCAuthType` to the database user service (endpoint: [createDatabaseUser](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v1/#tag/Database-Users/operation/createDatabaseUser))
=> INTMDB-931: Add support for OIDCAuthType to database user

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> release prep version 0.34.0

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go, mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Adds acceptDataRisksAndForceReplicaSetReconfig parameter in cluster and advanced cluster.
Ticket: [INTMDB-1236](https://jira.mongodb.org/browse/INTMDB-1236)
=> feat: Adds acceptDataRisksAndForceReplicaSetReconfig parameter in cluster and advanced cluster

.github/workflows/pr.yml
Uses go.mod version in Github Action instead of a specific version
=> chore: Uses go.mod version in Github Action instead of a specific version

mongodbatlas/backup_compliance_policy.go, mongodbatlas/backup_compliance_policy_test.go
As [per documentation](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v1/#tag/Cloud-Backups/operation/updateDataProtectionSettings), we are adding the two new fields `authorizedUserFirstName` and `authorizedUserLastName` to `backup_compliance_policy`.
Link to any related issue(s):  https://jira.mongodb.org/browse/INTMDB-1072
=> feat: adds fields to backup_compliance_policy.

README.md
The README file did not make it clear that this package is deprecated. Now it does.
=> chore: updates README to clarify deprecation.

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Adds field `ChangeStreamOptionsPreAndPostImagesExpireAfterSeconds` to ProcessArgs
Link to any related issue(s): CLOUDP-262526
=> feat: Adds field to ProcessArgs

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Adds AdvancedConfiguration attribute support in Cluster APIs.
Ref: https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Clusters/operation/createCluster 
Link to any related issue(s): [CLOUDP-296222](https://jira.mongodb.org/browse/CLOUDP-296222)
=> feat: Adds AdvancedConfiguration attribute
