GNUmakefile, README.md, mongodbatlas/containers.go, mongodbatlas/containers_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/project_ip_whitelist_test.go
Added Containers Service for VPC Containers API Calls.
=> Containers Service

mongodbatlas/mongodbatlas.go
Avoid further confusion with missing or not missing services
=> Chore: Sort the services alphabetically

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
=> Add cluster advaced configuration support

mongodbatlas/clusters.go
- Added missing comments
- Added omitempty tags for the ProcessArgs struct
=> Added missing comments and omitempty tags for the ProcessArgs struct

mongodbatlas/api_keys.go, mongodbatlas/api_keys_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/project_api_key_test.go, mongodbatlas/projects.go, mongodbatlas/projects_test.go, mongodbatlas/teams.go, mongodbatlas/teams_test.go
Added:
Teams to handle the API calls
Team Service Test cases
=> Teams Service

mongodbatlas/alert_configurations.go, mongodbatlas/alert_configurations_test.go, mongodbatlas/mongodbatlas.go
Added:
- Alert Configuration resource to handle the API calls
- Alert Configuration test cases
=> Alert Configuration

mongodbatlas/mongodbatlas.go, mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_test.go
Added:
- Private Endpoints resource to handle the API calls
- Private Endpoints test cases
=> Private Endpoints

mongodbatlas/mongodbatlas.go, mongodbatlas/x509_authentication_database_users.go, mongodbatlas/x509_authentication_database_users_test.go
Added:
- X509 to handle the API calls
- X509 test cases
=> X509 auth db users

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
I've just added the PitEnabled attribute in the Cluster struct and added it into the unit test cases.
=> feat: add pitEnabled attribute un clusters service

mongodbatlas/cloud_provider_snapshot_restore_jobs.go, mongodbatlas/cloud_provider_snapshots.go, mongodbatlas/continuous_snaphots.go, mongodbatlas/continuous_snapshots_test.go, mongodbatlas/mongodbatlas.go
Initial support for continuous backup
=> CLOUDP-58632: Add Continuous Backup Snapshots support for atlas go client

.travis.yml, GNUmakefile
These are just some minor improvements to travis to remove unused features and improve our coverage of go versions
=> Improve Travis

mongodbatlas/atlas_alerts.go, mongodbatlas/atlas_alerts_test.go, mongodbatlas/mongodbatlas.go
[CLOUDP-57632](https://jira.mongodb.org/browse/CLOUDP-57632): 
Implement the Atlas API resource for alerts, https://docs.atlas.mongodb.com/reference/api/alerts/
=> CLOUDP-57632: Implementing Alerts resource

mongodbatlas/continuous_restore_jobs.go, mongodbatlas/continuous_restore_jobs_test.go
the documentation may be wrong and this is the actual response, I'm confirming this internally
=> CLOUDP-58969: Create restore job returns a list and not a single job

mongodbatlas/cloud_provider_snapshot_backup_policies.go, mongodbatlas/cloud_provider_snapshot_backup_policies_test.go, mongodbatlas/mongodbatlas.go
Added:
- Cloud Provider Snapshot Backup Policy resource to handle the API calls
- Cloud Provider Snapshot Backup Policy test cases
=> Cloud Provider Snapshot Backup Policy

mongodbatlas/atlas_alerts.go, mongodbatlas/atlas_alerts_test.go, mongodbatlas/checkpoints.go
[CLOUDP-59435](https://jira.mongodb.org/browse/CLOUDP-59435)
=> CLOUDP-59435: Update alert list to use status in Atlas

mongodbatlas/mongodbatlas.go, mongodbatlas/processes.go, mongodbatlas/processes_test.go
Co-authored-by: J.P. Poveda <etsuo@users.noreply.github.com>
=> Add get processes in a group

CHANGELOG.md
I just want a quick review from you to check if all the items in the changelog are OK.
=> Update changelog for the new release

.github/pull_request_template.md, CODEOWNERS.md, CONTRIBUTING.md, README.md
Add a CONTRIBUTING file
Add a PR template
Improve README
[skip travis]
=> Improve docs

mongodbatlas/events.go, mongodbatlas/events_test.go
Add validation for required params
=> Fix event list options

mongodbatlas/projects.go, mongodbatlas/projects_test.go
**Breaking change**
Fix project lists to allow pagination
This is probably a breaking change as I'm changing the method signature but this may have been an oversight missing the pagination params
=> Fix projects lists

mongodbatlas/cloud_provider_snapshots.go, mongodbatlas/cloud_provider_snapshots_test.go
https://github.com/mongodb/go-client-mongodb-atlas/issues/95
Support the pagination of [CloudProviderSnapshotsService.GetAllCloudProviderSnapshots](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotsService) and [CloudProviderSnapshotsServiceOp.GetAllCloudProviderSnapshots](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotsServiceOp.GetAllCloudProviderSnapshots).
The signature of [CloudProviderSnapshotsService.GetAllCloudProviderSnapshots](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mongodbatlas?tab=doc#CloudProviderSnapshotsService) and [CloudProviderSnapshotsServiceOp.GetAllCloudProviderSnapshots](https://pkg.go.dev/github.com/mongodb/go-client-mongodb-atlas/mong …
=> feat: support the pagination at GetAllCloudProviderSnapshots

mongodbatlas/cloud_provider_snapshot_backup_policies.go, mongodbatlas/cloud_provider_snapshot_backup_policies_test.go
Closes https://github.com/mongodb/go-client-mongodb-atlas/issues/93
=> fix: fixes #93 CloudProviderSnapshotBackupPolicy zero values are ignored

CHANGELOG.md
Updated the changelog file for v0.3.0
=> Updated Changelog for v0.3.0 release

mongodbatlas/mongodbatlas.go, mongodbatlas/organizations.go, mongodbatlas/organizations_test.go
=> feat: adds organization API

mongodbatlas/containers.go, mongodbatlas/containers_test.go
While doing some testing I noticed this method was missing
=> feat: Add missing method to get all containers

mongodbatlas/processes.go, mongodbatlas/processes_test.go
Add missing filter for processes API
=> Add the ability to filter processes by cluster ID

mongodbatlas/mongodbatlas.go, mongodbatlas/online_archives.go, mongodbatlas/online_archives_test.go
Add support for the Online Archive API
=> CLOUDP-66608: Implement Online Archive in the Go client

mongodbatlas/data_lakes.go, mongodbatlas/data_lakes_test.go, mongodbatlas/mongodbatlas.go
=> CLOUDP-66607: Atlas Data Lakes

mongodbatlas/aws_custom_dns.go, mongodbatlas/aws_custom_dns_test.go, mongodbatlas/mongodbatlas.go
=> Add custom AWS DNS support

mongodbatlas/mongodbatlas.go
The lib version is really out of date, instead of us trying to remember to update it on anew tag is better to just remove it
=> Remove libraryVersion from user agent

README.md, mongodbatlas/doc.go
=> Updated the references to the digest library

GNUmakefile
=> test: update GOLANGCI_VERSION

mongodbatlas/private_endpoints.go
=> fix: fix typo on missing field error

CHANGELOG.md
- Updated changelog to v0.4.0
- changed dates as the Terraform changelog to have more coherency
=> chore: Updated changelog for v0.4.0

mongodbatlas/alert_configurations.go
=> Added threshold attribute

mongodbatlas/organizations.go
This is a new property that was added recently when listing organizations
=> feat: add IsDeleted to organizations

mongodbatlas/ldap_configurations.go, mongodbatlas/ldap_configurations_test.go, mongodbatlas/mongodbatlas.go
Added LDAP Configurations to atlas go client https://docs.atlas.mongodb.com/reference/api/ldaps-configuration/
=> CLOUDP-72643: Add LDAP Configurations to atlas go client

go.sum, mongodbatlas/mongodbatlas.go, mongodbatlas/performance_advisor.go, mongodbatlas/performance_advisor_test.go
Implemented Performance Advisor API call https://docs.atlas.mongodb.com/reference/api/performance-advisor/
=> CLOUDP-72746: Add Performance Advisor API call to atlas go client

mongodbatlas/mongodbatlas.go, mongodbatlas/project_ip_access_list.go, mongodbatlas/project_ip_access_list_test.go
Adds the new access list resource
=> feat: add access list API

.github_changelog_generator, CHANGELOG.md, RELEASING.md, mongodbatlas/mongodbatlas.go, scripts/release.sh
Update CHANGELOG and add a RELEASING doc with the things I had to do to get this going
=> chore: release prep

.github_changelog_generator, mongodbatlas/mongodbatlas.go
Setting everything for the next release
=> chore: update versions to next desired

mongodbatlas/alert_configurations.go
=> docs: fix AlertConfigurationsService docs

mongodbatlas/cloud_provider_access.go, mongodbatlas/cloud_provider_access_test.go, mongodbatlas/mongodbatlas.go
=> INTMDB-132: Add support for Cloud Provider Access

mongodbatlas/mongodbatlas.go, mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_deprecated.go, mongodbatlas/private_endpoints_deprecated_test.go, mongodbatlas/private_endpoints_test.go
Added two files for private endpoints and its tests and the old ones changed the name to `_deprecated` at the end of file.
=> INTMDB-122: Private Endpoints

mongodbatlas/private_endpoints.go
Added another parameter called `ID` for body request  of `InterfaceEndpointConnection`
=> Fix private endpoints

mongodbatlas/online_archives.go, mongodbatlas/online_archives_test.go
Online archive has changed some of its structs, this is a fix for that
=> fix: update online archive structs

mongodbatlas/encryptions_at_rest.go, mongodbatlas/encryptions_at_rest_test.go
Added parameters for AWS KMS:
- Role ID
- Valid
=> INTMDB-134: Added parameter roleId and valid for AWS KMS

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, README.md
Somehow we were missing an ISSUE_TEMPLATE for this repo
=> docs: add issue templates

.github_changelog_generator, mongodbatlas/mongodbatlas.go
Prepare master for the next release
=> INTMDB-138: Post release version bump

mongodbatlas/accesslist_api_keys.go, mongodbatlas/accesslist_api_keys_test.go, mongodbatlas/mongodbatlas.go
Added files for access list programmatic api keys 
=> INTMDB-139: Add access list for programmatic API keys

mongodbatlas/default_mongodb_major_version.go, mongodbatlas/default_mongodb_major_version_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
=> CLOUDP-80413: [go-client] add service to get default mongodb major version

mongodbatlas/data_lakes.go, mongodbatlas/data_lakes_test.go
Creating a data lake without these new fields will now fail
=> INTMDB-164: Update data lake to support new required fields for creation

mongodbatlas/clusters.go
=> INTMDB-165: Update connection strings for cluster

mongodbatlas/accesslist_api_keys.go, mongodbatlas/accesslist_api_keys_test.go
Updated the path of the AccessListAPIKeys Service from `accesslist` to `accessList`
=> INTMDB-173: Update the path of AccessListAPIKeys service

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
Moved the parameter `type` to correct object.
=> INTMDB-158: changed field type to another object

mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_test.go
Added azure status for Endpoint Service and renamed the name for aws status.
=> INTMDB-175: Added azure status in endpoint service

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> INTMDB-178: v0.7.2 Release prep

.github/workflows/pr.yml, GNUmakefile
Update the golangci-lint version to the latests
=> lint: update GOLANGCI_VERSION to 1.37.0

.github/workflows/pr.yml
We should update the go version in other places but I see the terraform provider still uses go 1.14 so for now just adding tests
=> build: add go1.16 tests

mongodbatlas/containers.go, mongodbatlas/containers_test.go
=> feat: add regions to GCP containers

mongodbatlas/cloud_provider_regions.go
The atlas endpoint `GET /api/atlas/v1.0/groups/{GROUP-ID}/clusters/provider/regions` has been recently updated and this PR updates the service in accordance with those changes
=> CLOUDP-86337: Update atlas region service to use new parameters - atlas go client

.github/workflows/pr.yml, .golangci.yml, GNUmakefile
=> task: update golangci-lint to 1.39.0

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release preparation

.github/CODEOWNERS, .github/dependabot.yml
Add a CODEOWNERS file and assign to APIx, also move dependabot to the same team
=> task: add CODEOWNERS

mongodbatlas/data_lakes.go, mongodbatlas/data_lakes_test.go
- Added field `AdditionalStorageClasses` for `DataLakeStore`
- Added field `MaxWildcardCollections`  for `DataLakeDatabase`
=> INTMDB-19: Added fields in datalake databases and stores

mongodbatlas/mongodbatlas.go
`CloudURL` was erroneously removed in #212. In this PR I am adding `CloudURL` again
=> Bug Fix: Add CloudURL

mongodbatlas/cloud_provider_snapshot_backup_policies.go, mongodbatlas/cloud_provider_snapshot_backup_policies_test.go
Added a function and its test for Delete Cloud Backup Schedules
=> INTMDB-145: Support delete function for Cloud Backup Schedules

mongodbatlas/cloud_provider_snapshot_backup_policies_test.go, mongodbatlas/continuous_snapshots.go
=> Fixed failing tests

mongodbatlas/alert_configurations.go, mongodbatlas/alert_configurations_test.go
=> fix: fix alert configurations path

.github/dependabot.yml
We tend to have Mondays off, we have done this with all other repos
=> task: check dependencies on Tuesday

mongodbatlas/advanced_clusters.go
=> Addded autoscaling to the advance cluster

mongodbatlas/search.go, mongodbatlas/search_test.go
Method to update all search analyzers was added
=> added update-all-analyzers method to search

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release 0.9.0 prep

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release 0.10.0 prep

mongodbatlas/atlas_users.go, mongodbatlas/atlas_users_test.go
Bug: The atlas user create was calling the wrong endpoint
=> Bug: The atlas user create was calling the wrong endpoint

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release 0.10.1 prep

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release 0.11.0 prep

mongodbatlas/live_migration.go, mongodbatlas/live_migration_test.go, mongodbatlas/mongodbatlas.go
Added [Cloud Migration endpoints](https://docs.atlas.mongodb.com/reference/api/live-migration/)
=> CLOUDP-97549: Add cloud migration endpoint to the atlas go client

mongodbatlas/live_migration.go, mongodbatlas/mongodbatlas.go
Renamed `LiveMigrationOp` to `LiveMigrationServiceOp`
=> Renamed LiveMigrationOp to LiveMigrationServiceOp

.github/workflows/pr.yml, go.mod
=> feat: update supported go versions

mongodbatlas/search_test.go
Add more unit tests for atlas search covering case where a field type would be an array/slice
Link to any related issue(s): [CLOUDP-98424](https://jira.mongodb.org/browse/CLOUDP-98424)
=> CLOUDP-98424: Add unit tests for atlas search

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release prep for 0.12.0

mongodbatlas/processes.go
=> docs: clarify processes ClusterID

go.sum
=> task: run go mod tidy

mongodbatlas/private_endpoints.go, mongodbatlas/private_endpoints_test.go
- Added fields and tests for GCP features in Private Endpoints
=> INTMDB-260: Added for gcp features in private endpoints

.github/workflows/pr.yml, GNUmakefile, mongodbatlas/accesslist_api_keys.go, mongodbatlas/accesslist_api_keys_test.go, mongodbatlas/api_keys.go, mongodbatlas/api_keys_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go, mongodbatlas/project_api_key.go, mongodbatlas/whitelist_api_keys.go, mongodbatlas/whitelist_api_keys_test.go
Updating the lint, `ioutil` is now flagged as deprecated and gosec is detecting some more false positive
=> CLOUDP-105826: Update golangci-lint to 1.43

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release prep

mongodbatlas/clusters.go, mongodbatlas/clusters_test.go
- Added a new parameter for clusters called `VersionReleaseSystem`
- Added tests 
=> INTMDB-276: Added parameter versionReleaseSystem in clusters

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
Release preparation for 0.15.0
=> task: Release prep for 0.15.0

.github/workflows/pr.yml, GNUmakefile
Adds go1.18 to the test matrix
=> tas: add go 1.18 to the test matrix

mongodbatlas/live_migration.go, mongodbatlas/live_migration_test.go
=> feat: add ready for cutover field to live migrations

auth/device_flow.go
=> CLOUDP-118714 add IsTimeoutErr func

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release v0.16.0 preparations

.github/workflows/pr.yml
=> task: add tests against 1.19

mongodbatlas/advanced_clusters.go
=> Revert CLOUDP-132967: add the ability to use yaml file for advance cluster 

mongodbatlas/clusters.go, mongodbatlas/serverless_instances.go, mongodbatlas/serverless_instances_test.go
=> CLOUDP-132512: [Atlas CLI] Add support for updating a serverless cluster

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release 0.17.0 prep

.github_changelog_generator, CHANGELOG.md, mongodbatlas/advanced_clusters.go, mongodbatlas/mongodbatlas.go
=> task: Release 0.18.0 prep

.github/workflows/stale.yml, CONTRIBUTING.md, mongodbatlas/advanced_clusters.go
=> CLOUDP-79100: Autoclose stale issues and PRs

mongodbatlas/alert_configurations.go, mongodbatlas/alert_configurations_test.go
Add support for Webhook and MicrosoftTeamsWebhookURL Notifications
=> INTMDB-373: Add support for Webhook and MicrosoftTeamsWebhookURL Notifications

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go
This PR adds `analyticsAutoScaling` to Advanced Cluster
=> CLOUDP-143634: Add analyticsAutoScaling to advanced cluster atlas go client

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: Release 0.19.0 prep

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release prep for 0.20.0

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> task: release prep for 0.21.0

mongodbatlas/advanced_clusters.go, mongodbatlas/advanced_clusters_test.go
Add the test failover endpoint 
=> feat: add test failover method

v2/tools/package-lock.json, v2/tools/package.json, v2/tools/transformer/README.md, v2/tools/transformer/__tests__/input.json, v2/tools/transformer/__tests__/transformations-cases.js, v2/tools/transformer/__tests__/transformations.test.js, v2/tools/transformer/src/transform.js, v2/tools/transformer/src/transformations.js, v2/tools/transformer/src/utils.js
Required tools for SDK. New files only in [1b19c45](https://github.com/mongodb/go-client-mongodb-atlas/pull/347/commits/1b19c459d2d56f12c77ac410018b1b54c0ffc90b)
=> CLOUDP-155262: sdk required tools

mongodbatlas/cluster_outage_simulation.go, mongodbatlas/cluster_outage_simulation_test.go, mongodbatlas/mongodbatlas.go, mongodbatlas/mongodbatlas_test.go
Add Outage simulation endpoints
=> feat: add outage simulation

v2/Makefile, v2/tools/README.md, v2/tools/scripts/fetch.sh, v2/tools/scripts/generate.sh
Minimal scripts and automation for handling versioned SDK:
Scripts separate different concerns:
- Fetching inputs
- Processing and Generation
Follow up: CI/CD process using that scripts.
=> CLOUDP-155262: scripts and automation for source code generation

.github/workflows/shellcheck.yml, githooks/pre-commit, v2/tools/scripts/fetch.sh, v2/tools/scripts/generate.sh
Adding shellcheck for scripts and automation.
=> CLOUDP-155262: shellcheck scripts

v2/test/regresion_test.go, v2/test/regression/database_users.go, v2/test/regression/multi_cloud_clusters.go, v2/test/regression/project_ip_address_list.go
I am adding regression tests to detect possible breaking changes in the happy path. 
Those tests would be only temporary as we would have breaking changes detection done by versioned API
=> CLOUDP-156527: add regression tests

.github/CODEOWNERS
=> CLOUDP-156187: change owners team to apix-1

api/examples/example_cluster_aws.go, api/v2/atlas_client.go, tools/config/go-templates/atlas_client.mustache
=> CLOUDP-157231: add customisation for user agent

tools/Makefile, tools/config/go-templates/atlas_client.mustache, tools/scripts/fetch.sh, tools/scripts/generate.sh
Improvements in generation script to not expose variables that are internal - further formalising generation API
=> CLOUDP-155911: formalize generation parameters

api/v1alpha/atlas_client.go, tools/config/go-templates/atlas_client.mustache
Trim needs to happen only for custom url as production base url is set as constant.
=>  CLOUDP-161238 trim base url on the client

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
Minor update after some QA on the CLI confirming this works now as expected
=> task: release 0.23.1 prep

.github/workflows/autoupdate.yaml
Extends https://github.com/mongodb/go-client-mongodb-atlas/pull/397 
Needed separate PR as I'm using different base branch
=> CLOUDP-162109: note for the job

.github/workflows/shellcheck.yml, tools/scripts/fetch.sh, tools/scripts/generate.sh
WHY: Minimizing the number of runs of jobs for scheduled PRs.
=> Update shellcheck job to run only when sh files are changed

RELEASING.md
Minor: update release notes with sdkv2 branch compatibility.
This is only temporary until sdkv2 will be merged to master (I hope soon)
=> docs: add release note update

.github/workflows/autoupdate-dev.yaml
Rename PR description to differentiate between daily production updates and daily dev update PRs.
=> Rename automation PR

mongodbatlasv2/api_atlas_search.go, mongodbatlasv2/api_cloud_backups.go, mongodbatlasv2/api_cloud_migration_service.go, mongodbatlasv2/api_data_federation.go, mongodbatlasv2/api_data_lake_pipelines.go, mongodbatlasv2/api_database_users.go, mongodbatlasv2/api_federated_authentication.go, mongodbatlasv2/api_legacy_backup.go, mongodbatlasv2/api_maintenance_windows_.go, mongodbatlasv2/api_multi_cloud_clusters.go, mongodbatlasv2/api_network_peering.go, mongodbatlasv2/api_online_archive.go, mongodbatlasv2/api_organizations.go, mongodbatlasv2/api_private_endpoint_services.go, mongodbatlasv2/api_programmatic_api_keys.go, mongodbatlasv2/api_project_ip_access_list.go, mongodbatlasv2/api_projects.go, mongodbatlasv2/api_serverless_instances.go, mongodbatlasv2/api_serverless_private_endpoints.go, mongodbatlasv2/api_teams.go, mongodbatlasv2/api_third_party_integrations.go, mongodbatlasv2/model_error.go, openapi/atlas-api-transformed.yaml, tools/transformer/src/atlasTransformations.js
Changes are functional in the dev branch as we tested, but they still not available in production.
We need to keep workarounds for some time. I created jira to remove them in GA epic.
=> chore: reintroduce transformer workarounds

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
We want to release Atlas Go client to support [INTMDB-587](https://jira.mongodb.org/browse/INTMDB-587) with changes in PR https://github.com/mongodb/go-client-mongodb-atlas/pull/453
=> INTMDB-751: 0.25.0 pre-release

README.md, examples/example_cluster_aws.go, openapi/atlas-api.yaml, sdk/errors.go
Add error handling for the sdk with documentation
=> Add error handling for SDK

.github/workflows/pr.yml, GNUmakefile
Make go tests use stable and previous stable as versions so we can make these variants mandatory on PRs
=> test: update actions to use the new go action values

tools/transformer/__tests__/transformations.test.js, tools/transformer/src/engine/readers.js, tools/transformer/src/engine/transformers.js, tools/transformer/src/transformations/allOf.js
`allOf` references to parents that have no properties or required properties should be removed as part of the `allOf` transformation.
Before:
```
CreateEndpointRequest:
type: object
oneOf:
- $ref: "#/components/schemas/CreateAWSEndpointRequest"
- $ref: "#/components/schemas/CreateAzureEndpointRequest"
- $ref: "#/components/schemas/CreateGCPEndpointGroupRequest"
CreateAWSEndpointRequest:
type: object
allOf:
- $ref: '#/components/schemas/ApiAtlasCreateEndpointRequestView'
- type: object
properties: ...
CreateAzureEndpointRequest:
type: object
allOf:
- $ref: '#/components/schemas/ApiAtlasCreateEndpointRequestView'
- type: object
properties: ...
CreateGCPEndpointGroupRequest:
type: object
allOf:
- $ref: '#/components/schemas/ApiAtlasCreateEndpointRequestView'
- type: object
properties: ... …
```
=> fix: enable allOf transformation for parents without properties

mongodbatlas/data_lakes_pipeline.go, mongodbatlas/data_lakes_pipeline_test.go, mongodbatlas/mongodbatlas.go
This PR adds [Data Lake Pipeline](https://www.mongodb.com/docs/atlas/reference/api-resources-spec/#tag/Data-Lake-Pipelines) support to the go client. 
=> INTMDB-804: Add Data lakes pipeline support

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> v0.29.0 pre-release

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> v0.30 release prep

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> v0.31.0 release prep

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> release prep 0.33

mongodbatlas/alert_configurations.go, mongodbatlas/alert_configurations_test.go
Ticket: [INTMDB-981](https://jira.mongodb.org/browse/INTMDB-981)
=> feat: add notifierId parameter in alert configuration notifications

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> release prep version 0.35.0

RELEASING.md
=> chore: Updates release doc

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> release prep version 0.36.0

go.mod
Follow up to ff8770019675bebbd95326c14536a475b89161bd to make it discoverable via code
=> task: Deprecated go.mod

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
=> release prep version 0.37.0

.github_changelog_generator, CHANGELOG.md, mongodbatlas/mongodbatlas.go
This PR updates the repo for the next 0.38.0 release.
Link to any related issue(s): [CLOUDP-296222](https://jira.mongodb.org/browse/CLOUDP-296222)
=> chore: Release 0.38.0 changelog & version update
